[package]
name = "crate-deps"
version = "0.1.2"
authors = ["Christian Sharpsten <christian.sharpsten@gmail.com>"]
edition = "2021"
description = "Compute a rust crate's dependency tree"
license = "MIT"

[dependencies]
anyhow = "1.0.82"
cargo = "0.78.1"
semver = "1.0.22"
thiserror = "1.0.59"
